### ISSUE TITLE
linux build pls

### ISSUE THREAD

**Issue by gmankab** [epsilon8eridani/Songsterr-tab-downloader#1]

**Comment by eridani137** [comment]
[check](https://github.com/epsilon8eridani/Songsterr-tab-downloader/releases/tag/v1.0.0)

**Comment by gmankab** [comment]
thanks for the quick response

it runs but throws error

![image](https://github.com/epsilon8eridani/Songsterr-tab-downloader/assets/73340745/d2484e19-3218-4108-8f6b-0aade019e911)

**Comment by eridani137** [comment]
It works for me with WSL and Ubuntu. Try using a VPN

**Comment by gmankab** [comment]
i tried vpn, nothing changes

also i tried to choose `download multiple tabs from search url` mode, with this link - https://www.songsterr.com/?pattern=anacondaz

it downloaded first two songs, then throwed an error

![image](https://github.com/epsilon8eridani/Songsterr-tab-downloader/assets/73340745/518ee744-fdc0-460b-9b94-915281a50ef2)

**Comment by eridani137** [comment]
Greetings, restored functionality and build for linux

**Comment by gmankab** [comment]
thank you ❤️
